spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://localhost:5433/g_44_shop
    username: postgres
    password: pos1234
    driver-class-name: org.postgresql.Driver



  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml




server:
  servlet:
    context-path: /api
